# -*- coding: utf-8 -*-
"""train sentiment model .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhK_8qsYnMkx8DiHkG1yCwYhmUlxL6dy
"""

pip install pandas numpy scikit-learn nltk beautifulsoup4 joblib

import pandas as pd
import numpy as np
import re
import nltk
from bs4 import BeautifulSoup
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import joblib

# ---------------------------
# Step 1: Load Dataset
# ---------------------------
df = pd.read_csv("/content/IMDB Dataset.csv")  # Change path if needed
print("✅ Data Loaded")

# ---------------------------
# Step 2: Download Stopwords
# ---------------------------
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# ---------------------------
# Step 3: Clean Text Function
# ---------------------------
def clean_review(review):
    review = BeautifulSoup(review, "html.parser").get_text()  # Remove HTML
    review = re.sub("[^a-zA-Z]", " ", review)  # Remove non-letters
    words = review.lower().split()  # Lowercase
    words = [w for w in words if w not in stop_words]  # Remove stopwords
    return " ".join(words)

# ---------------------------
# Step 4: Apply Cleaning
# ---------------------------
df['cleaned_review'] = df['review'].apply(clean_review)
print("✅ Reviews cleaned")

# ---------------------------
# Step 5: Convert Sentiment to Numeric
# ---------------------------
df['sentiment'] = df['sentiment'].map({'positive': 1, 'negative': 0})

# ---------------------------
# Step 6: Feature Extraction with TF-IDF
# ---------------------------
tfidf = TfidfVectorizer(max_features=5000)
X = tfidf.fit_transform(df['cleaned_review']).toarray()
y = df['sentiment']
print("✅ Text vectorized")

# ---------------------------
# Step 7: Train-Test Split
# ---------------------------
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ---------------------------
# Step 8: Train Logistic Regression
# ---------------------------
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)
print("✅ Model trained")

# ---------------------------
# Step 9: Evaluate Model
# ---------------------------
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("✅ Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# ---------------------------
# Step 10: Save Model and Vectorizer
# ---------------------------
joblib.dump(model, "sentiment_model.pkl")
joblib.dump(tfidf, "vectorizer.pkl")
print("✅ Model and vectorizer saved")